#!/bin/bash

# define step's variables
eman \
  defvar FORMAT help='date format string' default='%Y-%m-%d %H:%M:%S' \
  defvar UTC help='diplay UTC' default='' \
  || exit 1

# load variable values
eval `eman bash-loadvars`

# INIT_ONLY is set by eman when step is only to be initialized 
# (not prepared/run), exit here in that case (do not create
# eman.command)
[ -z "$INIT_ONLY" ] || exit 0

cat << END > eman.command
#!/bin/bash
# This is the command to be run here
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="

mydir=\$(pwd)
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }

[ -z "$FORMAT" ] || dateargs=" +'$FORMAT' "
[ "$UTC" != "yes" ] || dateargs="\$dateargs -u "

eval "date \$dateargs" > date.out || die "Failed to run 'date'"

# Standard command footer
echo Done.
eman succeed \$mydir
echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
END
