#!/bin/bash

# define step's variables
eman \
  defvar DATESTEP help='step of type getdate' type=reqstep \
  defvar DIGITS help='which digits to count' \
  || exit 1

# load variable values
eval `eman bash-loadvars`

# ask eman for full step path
DATEPATH=`eman path $DATESTEP`

# Stop here if we are just initing ourselves
[ -z "$INIT_ONLY" ] || exit 0

cat << END > eman.command
#!/bin/bash
# This is the command to be run here
echo "=============================="
echo "== Started:   "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="

mydir=\$(pwd)
function die() { echo "\$@" >&2 ; eman fail \$mydir ; exit 1 ; }

cat $DATEPATH/date.out | tr -cd '$DIGITS' | wc -c > digitcount

# Standard command footer
echo Done.
eman succeed \$mydir
echo "=============================="
echo "== Ended:     "\`date '+%Y%m%d-%H%M'\`
echo "== Hostname:  "\`hostname\`
echo "== Directory: "\`pwd\`
echo "=============================="
END
